connection_restore: Соединение восстановлено данные были синхронизированы